services:
    app-django-django-general-utils-dev:
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile
        command: bash -c "uv run pytest -n 6"
        volumes:
            - ./:/usr/src/app
